// Package internal contains the core types and logic for ccAgents.
package internal

// Issue represents a GitHub issue fetched via the GitHub CLI
type Issue struct {
	Number     int    `json:"number"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	Repository string `json:"repository"`
	URL        string `json:"url"`
}

// CodeChanges represents the code changes generated by Claude
type CodeChanges struct {
	Files        map[string]string `json:"files"`          // path -> content
	NewFiles     []string          `json:"new_files"`
	DeletedFiles []string          `json:"deleted_files"`
	Summary      string            `json:"summary"`
}
