name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check formatting
        run: deno fmt --check src/main.ts src/processor.ts src/types.ts
      - name: Lint
        run: deno lint src/main.ts src/processor.ts src/types.ts
      - name: Test
        run: deno test --allow-all --coverage=cov
        env:
          DENO_TLS_CA_STORE: system
      - name: Generate coverage report
        run: deno coverage cov --lcov > coverage.lcov
